### ISSUE TITLE
pls update xnu-6153.11.26

### ISSUE THREAD

**Issue by stopkill70** [Shaneee92/AMD-High-Sierra-XNU#10]
https://opensource.apple.com/source/xnu/xnu-6153.11.26/

**Comment by Shaneee** [comment]
We don't need to compile the kernel anymore, https://github.com/AMD-OSX/AMD_Vanilla

**Comment by stopkill70** [comment]
You don’t think that building the kernel from the code with the patches will make it more stable. work?

**Comment by Shaneee** [comment]
> You don’t think that building the kernel from the code with the patches will make it more stable. work?

No, Patching the kernel on the fly is more stable. When we compile the xnu it misses out many things. This is why it's possible to get Apple iServices working with the bootloader patches rather than a compiled kernel.
