### ISSUE TITLE
Build environment questions

### ISSUE THREAD

**Issue by palxex** [Shaneee92/AMD-High-Sierra-XNU#11]
Hi, due to vanilla patches lacks OPEMU and latest crossover depends on it, I'm trying compile this patched kernel source as a start:) but my build refuse to boot. Could you help me figure what may cause the problem?

Environment: 
Vanilla 10.13.6 installation, installing with [IOIIIO's guide](https://101110.gitbook.io/workspace/), with [the kernel in releases](https://github.com/Shaneee/AMD-High-Sierra-XNU/releases/download/3.0.0/Shaneee_10.13.6.zip).
Xcode 9.4.1, the last version that has macosx10.13 SDK builtin.

Situation: 
Everytime after new kernel compiled and prelinked, reboot and KP will happen after several minutes. 
![IMG_790B32CC7637-1](https://user-images.githubusercontent.com/58222/91217100-92d0ae80-e749-11ea-9280-0a1305d92eb5.jpeg)
And when restore downloaded kernel and re-prelink in catalina the 10.13.6 partition will boot again...

By compiling the kernel, I'm following [Scott Knight's guide](https://knight.sc/debugging/2018/12/10/building-xnu.html), only changing all version to [corresponding 10.13.6 versions](https://opensource.apple.com/release/macos-10136.html):
```
AvailabilityVersions-32.60.1
dtrace-262.50.12
libdispatch-913.60.2 
libplatform-161.50.1
```
If any step( or library/compiler version setup ) is different than yours when you compiling the mentioned kernel, please tell me!
BTW: Seems behavior of apple toolchain varying heavily between major releases. In the beginning I'm trying compiling with Xcode 11.6, but it reports error on absolutely correct i386 at&t assembly syntax in idt64.c, maybe it have dropped i386 asm support?

**Comment by Shaneee** [comment]
I used Xcode 9.2 to build the 10.13.x source.

**Comment by palxex** [comment]
Thanks for your reply:) seems it's not root cause, recompile with Xcode 9.2 got same error ( busy timeout[x], (60s): 'AppleACPICPU' several times and finally KP ).
This time I got a panic log. Unfortunately core dump never done.
[saved_panic.txt](https://github.com/Shaneee/AMD-High-Sierra-XNU/files/5128138/saved_panic.txt)
Steps after kernel making done, could you please check whether something lacks?
```
sudo cp BUILD/obj/DEBUG_X86_64/kernel.debug /System/Library/Kernels/kernel
sudo ditto BUILD.syskext / #which contains System.kext and Kernel.framework)
sudo chown -R root:wheel /System/Library/Extensions /Library/Extensions
sudo chmod -R 755 /System/Library/Extensions /Library/Extensions
sudo touch /System/Library/Extensions /Library/Extensions
sudo kextcache -u /
sudo reboot
```
Since the Clover configuration works well on your kernel, I assume  nothing need change on the my build. If it's not true, please tell me upload it or describe each component version in detail.

**Comment by Shaneee** [comment]
Try this script for setting up the build env, https://gist.github.com/afrighetto/e47b990f52586b4797297e7548e6352c/archive/d333e579050c52903b6063560aef536cadc72963.zip

I recommend placing it in a folder in the Documents folder so for example Documents/BuildXNU.

```
cd Documents/BuildXNU
MACOS_VERSION=10.13.6 ./build-xnu.sh
```

That what I was using the get the system ready to build.
What changes are you making to the kernel source?

I've also just realised your copying kernel.debug... This won't work on AMD. You'll need to use `BUILD/obj/RELEASE_X86_64/kernel`

**Comment by palxex** [comment]
OH MY. just changed to release it boots- - thanks very much for the tip!
(In later test, even 9.4.1 release build also boots well)

> What changes are you making to the kernel source?

Currently no any change. I'm planning debug OPEMU on 10.13 after able to build xnu. but...

> debug won't work on AMD

Er...Then do we have any method debugging AMD specific kernel, like enable KDP on release kernel?

**Comment by palxex** [comment]
Finished validating opemu functional code on crossover 19 support by compile/reboot looping, seems debugging not needed. Thanks for your help!
