### ISSUE TITLE
Audio stuttering issue on Ryzen 2200G

### ISSUE THREAD

**Issue by kk1987** [Shaneee92/AMD-High-Sierra-XNU#3]
See my forum post https://forum.amd-osx.com/viewtopic.php?p=43295#p43295

The audio stuttering issue on my Ryzen 2200G is only fixed with version 1.1.1 and 1.2.0. Both 2.0.0 and 3.0.0 seem to have regressions.

**Comment by Shaneee** [comment]
Will be fixed in next revision. We are working on a cleaner source.

Try this in the meantime, https://www.dropbox.com/s/ouroubgs199rmsx/10.13.6_Shaneee.zip?dl=0

**Comment by atthasd** [comment]
Hi Shaneee,

I’m having the same issue, from what i have before at 10.13.3, before the ryzen audio patch is appears also in 10.13.6. Audio stuttering when playing from vlc, mpv, spotify, but not in youtube streaming.

I used the kernel in the link above but i can’t boot.

Hoping that the release of 10.13.6 revision is still there. As i am using Pascal GPU, can’t upgrade to mojave just yet.

Thanks sir
