### ISSUE TITLE
can x4 638 be supported?

### ISSUE THREAD

**Issue by Wesley-Xi** [Shaneee92/AMD-High-Sierra-XNU#6]
If the answer is positive, I'll buy one to update my pc;
otherwise, I may contiune to use my a4 3400

**Comment by Shaneee** [comment]
I don't think that CPU has SSE4.1 so no it won't work.

**Comment by Wesley-Xi** [comment]
but it has SSE4a, did this help ? If not what proper edition can x4 638 support?
sierra or El Capitan ?

**Comment by Shaneee** [comment]
El Capitan is the highest version of macOS for that CPU. SSE4a is different from SSE4.1

**Comment by Wesley-Xi** [comment]
But as the amdosx web introduces, "Compiled by Shaneee this High Sierra kernel will boot on all AMD CPUs.". I think the SSE4.1 is not the key point that will prevent us of installing osx, it may just behave poorly when dealing with video tasks.
