### ISSUE TITLE
_intel_fast_memset.A 

### ISSUE THREAD

**Issue by gybiscus** [Shaneee92/AMD-High-Sierra-XNU#8]
Several applications crashes when launched. E.g. installer of Intel Parallel Studio, see attached crashlog:
[install_gui_2019-05-06-134320_tower.crash.zip](https://github.com/Shaneee92/AMD-High-Sierra-XNU/files/3147701/install_gui_2019-05-06-134320_tower.crash.zip)

**Comment by gybiscus** [comment]
When the simple code below compiled as "icc test.cpp -O1"

```
#include <stdio.h>

int main(int argc, char* argv[])
{
    printf("Hello, world!\n");
   int* p = new int [1000];
    for(int i=0; i<1000; i++) p[i] = 0;
    delete [] p;

    return 0;
}

```
runs flawlessly and produces output:
```
bash-3.2$ lldb a.out 
(lldb) target create "a.out"
Current executable set to 'a.out' (x86_64).
(lldb) r
Process 2716 launched: '/Users/user/Desktop/intel-ryzen-hackintosh/a.out' (x86_64)
Hello, world!
Process 2716 exited with status = 0 (0x00000000) 

```
On the other hand the same program compiled with command "icc test.cpp -O2"
gives a similar "_intel_fast_memset" crash:
```
bash-3.2$ lldb a.out 
(lldb) target create "a.out"
Current executable set to 'a.out' (x86_64).
(lldb) r
Process 2724 launched: '/Users/user/Desktop/intel-ryzen-hackintosh/a.out' (x86_64)
Hello, world!
Process 2724 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x7ffeef3ffff8)
    frame #0: 0x0000000100002c51 a.out`_intel_fast_memset.A + 1
a.out`_intel_fast_memset.A:
->  0x100002c51 <+1>: callq  0x100002ca0               ; _intel_fast_memset
    0x100002c56 <+6>: popq   %rcx
    0x100002c57 <+7>: retq   
    0x100002c58 <+8>: nopl   (%rax,%rax)
Target 0: (a.out) stopped.

```

**Comment by Shaneee** [comment]
This is app specific not kernel related.

**Comment by gybiscus** [comment]
If so why this crash does not occurred on the intel cpu based hackintosh? I suspect that _intel_fast_memset implementation relies on some cpu-specific intrinsics which probably does not work as it should on the ryzen with the patched kernel. May be I need to gather a more diagnostic info to find out the root of this issue, what do you think? Anyway thanks a lot for your incredible and useful work, Shaneee92!

**Comment by mmartain** [comment]
Well, according to this post, i would conclude there is a possibility it could be patched in the kernel:

https://forums.macrumors.com/threads/mp3-1-others-sse-4-2-emulation-to-enable-amd-metal-driver.2206682/post-28556400

**Comment by naveenkrdy** [comment]
@gybiscus hi !
works fine here.

![Screen Shot 2020-07-07 at 9 40 09 PM](https://user-images.githubusercontent.com/18463250/86810425-8067bc00-c09a-11ea-8d09-a60a69c2bf68.png)

if the app that you are using uses intel fast mem set then patch it to use _intel_fast_memset.V path instead of _intel_fast_memset.A in the binary.

**Comment by mmartain** [comment]
> @gybiscus hi !
> works fine here.
> 
> ![Screen Shot 2020-07-07 at 9 40 09 PM](https://user-images.githubusercontent.com/18463250/86810425-8067bc00-c09a-11ea-8d09-a60a69c2bf68.png)
> 
> if the app that you are using uses intel fast mem set then patch it to use _intel_fast_memset.V path instead of _intel_fast_memset.A in the binary.

How would somebody patch existing binaries to use the V instead of the A? Could this be done on a kernel level?
